apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-05-25T15:50:58Z"
  name: bigip-controller-role
  resourceVersion: "2047983"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/bigip-controller-role
  uid: 6f61211a-3d44-40df-8192-48d9b39de7e8
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - services
  - namespaces
  - secrets
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - patch
