apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-05-25T15:50:58Z"
  name: bigip-controllers
  resourceVersion: "2047984"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/bigip-controllers
  uid: cf057869-23a1-4cbf-bb6d-aef8bfd9aa2e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-controller-role
subjects:
- kind: ServiceAccount
  name: bigip-controller
  namespace: kube-system
